steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.frontend',
      '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/orderly/orderly-frontend:${_IMAGE_TAG}',
      '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/orderly/orderly-frontend:latest',
      '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}',
      '.'
    ]
    dir: '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '--all-tags',
      'asia-east1-docker.pkg.dev/$PROJECT_ID/orderly/orderly-frontend'
    ]

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/orderly/orderly-frontend:${_IMAGE_TAG}'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/orderly/orderly-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _IMAGE_TAG: 'latest'
  _NEXT_PUBLIC_API_BASE_URL: 'https://orderly-api-gateway-fastapi-staging-v2-655602747430.asia-east1.run.app/api'

timeout: '1800s'