/**
 * Mock Data for Acceptance Management
 * 驗收管理測試資料
 */

import type { AcceptanceRecord } from './types'

export const mockAcceptanceRecords: AcceptanceRecord[] = [
  {
    id: '1',
    orderId: 'order_123',
    orderNumber: 'ORD-2024-001',
    supplier: {
      name: '新鮮蔬果供應商',
      contact: '王經理',
      phone: '02-1111-2222',
    },
    acceptedBy: '張小明',
    acceptanceTime: '2024-01-16 14:25',
    acceptanceLocation: '台北店後門',
    items: [
      {
        id: '1-1',
        itemCode: 'VEG001',
        itemName: '有機高麗菜',
        orderedQuantity: 10,
        receivedQuantity: 10,
        unit: '公斤',
        qualityRating: 5,
        condition: 'excellent',
        expiryDate: '2024-01-20',
        notes: '品質優良，新鮮度佳',
        photos: ['photo1.jpg', 'photo2.jpg'],
      },
      {
        id: '1-2',
        itemCode: 'VEG002',
        itemName: '新鮮蘿蔔',
        orderedQuantity: 8,
        receivedQuantity: 7.8,
        unit: '公斤',
        qualityRating: 4,
        condition: 'good',
        notes: '稍有短收但品質良好',
        photos: ['photo3.jpg'],
      },
    ],
    overallRating: 4,
    notes: '整體驗收滿意，蘿蔔稍有短收',
    discrepancies: [
      {
        id: 'disc-1',
        type: 'quantity_short',
        severity: 'minor',
        itemCode: 'VEG002',
        description: '蘿蔔短收0.2公斤',
        evidencePhotos: ['evidence1.jpg'],
        proposedResolution: '接受短收，調整價格',
        financialImpact: -6,
      },
    ],
    status: 'completed',
    deliveryTime: '2024-01-16 14:20',
    requestedDeliveryTime: '2024-01-16 14:00',
  },
  {
    id: '2',
    orderId: 'order_124',
    orderNumber: 'ORD-2024-002',
    supplier: {
      name: '優質肉品供應商',
      contact: '李師傅',
      phone: '02-2222-3333',
    },
    acceptedBy: '陳小華',
    acceptanceTime: '2024-01-16 10:15',
    acceptanceLocation: '台北店後門',
    items: [
      {
        id: '2-1',
        itemCode: 'MEAT001',
        itemName: 'A級牛肉',
        orderedQuantity: 5,
        receivedQuantity: 5,
        unit: '公斤',
        qualityRating: 5,
        condition: 'excellent',
        temperature: 2,
        notes: '冷鏈保存良好',
        photos: ['meat1.jpg', 'temp1.jpg'],
      },
    ],
    overallRating: 5,
    notes: '冷鏈完善，品質優異',
    discrepancies: [],
    status: 'completed',
    deliveryTime: '2024-01-16 10:00',
    requestedDeliveryTime: '2024-01-16 10:00',
  },
  {
    id: '3',
    orderId: 'order_125',
    orderNumber: 'ORD-2024-003',
    supplier: {
      name: '海鮮直送',
      contact: '陳老闆',
      phone: '02-3333-4444',
    },
    acceptedBy: '林小美',
    acceptanceTime: '',
    acceptanceLocation: '台北店後門',
    items: [
      {
        id: '3-1',
        itemCode: 'FISH001',
        itemName: '新鮮鮭魚',
        orderedQuantity: 2,
        receivedQuantity: 1.5,
        unit: '公斤',
        qualityRating: 2,
        condition: 'poor',
        temperature: 8,
        notes: '溫度過高，有異味',
        photos: ['fish1.jpg', 'fish2.jpg'],
      },
    ],
    overallRating: 2,
    notes: '冷鏈斷鏈，品質不佳',
    discrepancies: [
      {
        id: 'disc-2',
        type: 'quality_issue',
        severity: 'critical',
        itemCode: 'FISH001',
        description: '鮭魚溫度過高，有異味',
        evidencePhotos: ['fish_temp.jpg', 'fish_smell.jpg'],
        proposedResolution: '退貨重送',
        financialImpact: -2400,
      },
    ],
    status: 'disputed',
    deliveryTime: '2024-01-15 08:30',
    requestedDeliveryTime: '2024-01-15 08:00',
  },
]
