apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://orderly-api-gateway-fastapi-staging-655602747430.asia-east1.run.app","https://orderly-api-gateway-fastapi-staging-usg6y7o2ba-de.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-east1
    environment: staging
    git_ref: staging
    git_sha: d910bcb5a6e08ed9c8c37e643b439cac3ee254d9
    service: api-gateway-fastapi
    version: d910bcb5a6e08ed9c8c37e643b439cac3ee254d9
  name: orderly-api-gateway-fastapi-staging
  namespace: '655602747430'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 539.0.0
        run.googleapis.com/cloudsql-instances: orderly-472413:asia-east1:orderly-db,orderly-472413:asia-east1:orderly-db-v2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: qzlawhtkdk
        environment: staging
        git_ref: staging
        git_sha: d910bcb5a6e08ed9c8c37e643b439cac3ee254d9
        run.googleapis.com/startupProbeType: Default
        service: api-gateway-fastapi
        version: d910bcb5a6e08ed9c8c37e643b439cac3ee254d9
    spec:
      containerConcurrency: 100
      containers:
      - env:
        - name: NODE_ENV
          value: staging
        - name: USER_SERVICE_URL
          value: https://orderly-user-service-fastapi-staging-usg6y7o2ba-de.a.run.app
        - name: ORDER_SERVICE_URL
          value: https://orderly-order-service-fastapi-staging-usg6y7o2ba-de.a.run.app
        - name: PRODUCT_SERVICE_URL
          value: https://orderly-product-service-fastapi-staging-655602747430.asia-east1.run.app
        - name: ACCEPTANCE_SERVICE_URL
          value: https://orderly-acceptance-service-fastapi-staging-usg6y7o2ba-de.a.run.app/acceptance
        - name: NOTIFICATION_SERVICE_URL
          value: https://orderly-notification-service-fastapi-staging-usg6y7o2ba-de.a.run.app
        - name: CUSTOMER_HIERARCHY_SERVICE_URL
          value: https://orderly-customer-hierarchy-service-fastapi-staging-655602747430.asia-east1.run.app
        - name: SUPPLIER_SERVICE_URL
          value: https://orderly-supplier-service-fastapi-staging-usg6y7o2ba-de.a.run.app
        - name: DATABASE_HOST
          value: /cloudsql/orderly-472413:asia-east1:orderly-db-v2
        - name: DATABASE_NAME
          value: orderly
        - name: DATABASE_USER
          value: orderly
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres-password
        - name: REDEPLOY_TIME
          value: 20250927-081918
        - name: DATABASE_URL
          value: postgresql+asyncpg://orderly:OtAEG5%2F1h78R%2BEGHStvtabQjOhjKtXNq%2FPse3d6ZTDs%3D@/orderly?host=/cloudsql/orderly-472413:asia-east1:orderly-db-v2
        image: asia-east1-docker.pkg.dev/orderly-472413/orderly/orderly-api-gateway-fastapi@sha256:0fef1b896d6e61c730b3f67b6b0a9848079810b6b812cf55d8b6e39e84b6588d
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: orderly-apigw-fastapi@orderly-472413.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
