steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'asia-east1-docker.pkg.dev/orderly-472413/orderly/orderly-supplier-service-fastapi:v1.0.1'
  - '-f'
  - 'backend/supplier-service-fastapi/Dockerfile'
  - '.'
images:
- 'asia-east1-docker.pkg.dev/orderly-472413/orderly/orderly-supplier-service-fastapi:v1.0.1'