name: Docs Link Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  docs-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docs reference checker
        shell: bash
        run: |
          bash scripts/check-doc-references.sh

